baseURL = '/'
languageCode = 'en-us'
title = 'My open-source home'
theme = 'hugo-book'
enableEmoji = true
enableInlineShortcodes = true

[params]
    BookTheme = 'light'
    BookToC = true

[markup.goldmark.renderer]
unsafe= true